### ISSUE TITLE
Failure to select certain format

### ISSUE THREAD

**Issue by akashpal-21** [christoph-heinrich/mpv-youtube-quality#38]
Sometimes --ytdl-format=22 as such fails to be selected from the quality menu, if I supply this directly the stream works fine.

```
[ytdl_hook] ERROR: [youtube]: Requested format is not available. Use --list-formats for a list of available formats
[ytdl_hook] youtube-dl failed: unexpected error occurred
AV: 00:00:07 / 01:18:41 (0%) A-V:  0.000 Cache: 10s/1MB
Failed to recognize file format.
```
I suspect this is a failure from the side of the quality menu selection to supply the correct format to yt-dlp.

Thanks,
Let me know how I can help further in this investigation.

PS: This is not limited to certain videos -- and sometimes it does select the correct format, but most times it fails, I suspect it is in parsing the correct format and passing it on

**Comment by christoph-heinrich** [comment]
I've tried that on a five videos now and it worked fine with all of them. I've also never noticed such a problem during general usage.

Please provide a log file by running mpv with `--log-file=log.txt` when that happens.
